name: LagFarmFinder
author: Ubertweakstor
date: 18/02/2013
main: ubertweakstor.lagfarmfinder.LagFarmFinder
version: 1.0.3

commands:
   findlag:
      description: This finds any laggy farms
      permission: lagfarmfinder.findlag
      usage: /<command> [parameters]
      permission-message: You don't have permission to execute this command.
      
   mobcount:
      description: Returns the number of entities near a player
      permission: lagfarmfinder.mobcount
      usage: /<command> [player] [radius]
      permission-message: You don't have permission to execute this command.